image: golang:1.10.1

before_script:
  - go clean
  - go get -u -v -fix github.com/bwmarrin/discordgo

build:
  stage: build
  script:
    - go build

test:
  stage: test
  script:
    - go test ./...
  allow_failure: true

gosec:
  stage: test
  script:
    - go get -u -v -fix github.com/securego/gosec
    - gosec .
  allow_failure: true