image: golang:1.10.1

before_script:
  - go get -u -v -fix gitlab.com/NatoBoram/Go-Miiko
  - go clean

build:
  stage: build
  script:
    - go build

test:
  stage: test
  script:
    - go test ./...
  allow_failure: true
